---
- name: Display specific ansible_facts
  hosts: RHEL
  tasks:
    - name: display specific facts
      ansible.builtin.debug:
        msg: >
          Host "{{ ansible_facts['fqdn'] }}" with Python version "{{ ansible_facts['python_version'] }}" has "{{ ansible_facts['processor_count'] }}" processors and "{{ ansible_facts['memtotal_mb'] }}" MiB of total system memory.
