---
- name: Enable intranet services
  hosts: RHEL
  become: true
  tasks:
    - name: Latest version of httpd and firewalld installed
      ansible.builtin.dnf:
        name:
          - httpd
          - firewalld
        state: latest

    - name: Test html page is installed
      ansible.builtin.copy:
        content: "Welcome to the example.com intranet! \n"
        dest: /var/www/index.html

    - name: Firewall enabled and running
      ansible.builtin.service:
        service: firewalld
        enabled: true
        state: started
    # Envían los argumentos necesarios para garantizar que se permitan conexiones HTTP remotas permanentemente.
    - name: Firewall permits access to httpd service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

- name: Test instranet web server
  hosts: RHEL2
  become: false
  tasks:
    # Ejecutar una consulta de contenido web del nodo de control al host administrado y verifican el código de estado recibido.
    - name: Connect to intranet web server
      ansible.builtin.uri:
        url: http://servera.lab.example.com
        return_content: yes
        status_code: 200
