---
- name: Crear usuario
  hosts: RHEL
  become: true
  remote_user: root
  vars_files:
    - secret.yml
  tasks: 
    - name: Crear usuario con secret.yml
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}"
